/* ─────────────────────────────────────────────
   DATA.JS — Game database with Roblox universe IDs
   universeId: used for Roblox thumbnail API
   placeId:    used for direct Roblox.com link
   ───────────────────────────────────────────── */

window.RP = window.RP || {};

RP.GAMES = [
  /* ── FPS / COMBAT ─────────────────────────── */
  {
    id: 'phantom-forces',
    title: 'Phantom Forces',
    creator: 'StyLiS Studios',
    genre: 'fps',
    emoji: '🔫',
    desc: 'The gold standard of Roblox FPS. Realistic ballistics, a massive weapon arsenal with customization, diverse maps, and a progression system built entirely around aim and strategy.',
    fullDesc: 'Phantom Forces is the definitive Roblox first-person shooter experience. Developed by StyLiS Studios, it features true-to-life ballistics, bullet drop, and recoil patterns across a roster of 100+ weapons. Each weapon can be customized with barrels, sights, and grips. Maps range from tight indoor corridors to sprawling outdoor battlefields. The ranking system rewards time and skill equally, and there\'s no pay-to-win element — every weapon is unlockable through gameplay.',
    tags: ['Team Deathmatch', 'Battle Royale', 'Competitive', 'Ranked'],
    rating: 97,
    players: 50000,
    playersLabel: '~50K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: false,
    featured: true,
    trending: true,
    year: 2015,
    universeId: 292439477,
    placeId: 292439477,
    modes: ['Team Deathmatch', 'Capture the Flag', 'Kill Confirmed', 'Flare Domination'],
  },
  {
    id: 'arsenal',
    title: 'Arsenal',
    creator: 'ROLVe Community',
    genre: 'fps',
    emoji: '🪖',
    desc: 'Gun game perfected. Cycle through weapons with each kill, fast-paced rounds, and a cosmetic system that never touches gameplay balance.',
    fullDesc: 'Arsenal brings the classic "Gun Game" format to Roblox. Every kill advances you to a new weapon — reach the end, win the round. Matches are fast (under 10 minutes), rewards are cosmetic-only, and the skill ceiling is surprisingly high. The game regularly updates with new maps, seasonal events, and limited cosmetics.',
    tags: ['Gun Game', 'Fast Paced', 'Cosmetics', 'Classic'],
    rating: 94,
    players: 30000,
    playersLabel: '~30K active',
    badge: 'classic',
    badgeText: '🏛 Classic',
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: true,
    trending: false,
    year: 2015,
    universeId: 286090429,
    placeId: 286090429,
    modes: ['Standard', 'Competitive', 'Randomizer'],
  },
  {
    id: 'bad-business',
    title: 'Bad Business',
    creator: 'typ_ical',
    genre: 'fps',
    emoji: '💥',
    desc: 'Clean, smooth FPS with excellent gunplay. Polished hit registration, great map variety, and monetization that never blocks gameplay.',
    fullDesc: 'Bad Business stands out for its technical quality. Hit detection is some of the best on Roblox, the weapon balance is thoughtful, and all maps are well-designed for competitive play. The developer consistently listens to the community, and the game has remained free of pay-to-win mechanics since launch.',
    tags: ['TDM', 'Smooth Gunplay', 'Fair Play'],
    rating: 90,
    players: 15000,
    playersLabel: '~15K active',
    badge: null,
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: false,
    year: 2019,
    universeId: 4471214961,
    placeId: 4471214961,
    modes: ['Team Deathmatch', 'Free For All'],
  },
  {
    id: 'entry-point',
    title: 'Entry Point',
    creator: 'Cishshato',
    genre: 'fps',
    emoji: '🕵️',
    desc: 'A genuine stealth-action heist game. Plan missions, coordinate with teammates, and choose between ghost stealth or going loud — with real consequences for each.',
    fullDesc: 'Entry Point is genuinely unlike anything else on Roblox. It plays like a proper heist game — each mission has multiple objectives, civilian management, and a stealth/loud split that changes the entire gameplay loop. Classes, equipment loadouts, and cooperative strategy make this feel like a full game rather than a Roblox experience.',
    tags: ['Stealth', 'Heist', 'Co-op', 'Mission-Based'],
    rating: 96,
    players: 8000,
    playersLabel: '~8K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'hard',
    mp: true,
    beginner: false,
    gem: false,
    featured: true,
    trending: false,
    year: 2018,
    universeId: 1480475871,
    placeId: 1480475871,
    modes: ['Story', 'Freelance', 'Practice'],
  },
  {
    id: 'counter-blox',
    title: 'Counter Blox',
    creator: 'ROLVe Community',
    genre: 'fps',
    emoji: '🎯',
    desc: 'CS:GO-inspired tactical shooter with bomb defusal, ranked matchmaking, and an economy system. One of the most strategically deep FPS games on the platform.',
    fullDesc: 'Counter Blox adapts CS:GO\'s core formula faithfully — terrorist vs counter-terrorist, bomb defusal, economy round management, and ranked competitive play. The game requires teamwork, communication, and deep understanding of map geometry. If you want the thinking-person\'s FPS, this is it.',
    tags: ['Tactical', 'Competitive', 'Economy', 'Ranked'],
    rating: 88,
    players: 5000,
    playersLabel: '~5K active',
    badge: null,
    diff: 'hard',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: false,
    year: 2016,
    universeId: 301549380,
    placeId: 301549380,
    modes: ['Competitive', 'Casual', 'Deathmatch'],
  },
  {
    id: 'bedwars',
    title: 'BedWars',
    creator: 'Easy.gg',
    genre: 'fps',
    emoji: '🛏️',
    desc: 'Protect your bed while destroying others. Strategic resource management meets PvP combat in this polished, ever-evolving game.',
    fullDesc: 'BedWars on Roblox is a full reimagining of the classic game mode. Gather resources, buy upgrades, protect your bed, and eliminate other teams. Regular updates add new maps, kits, and seasons. The game requires both strategic thinking and mechanical skill — a rare combination.',
    tags: ['PvP', 'Strategy', 'Team', 'Resource Management'],
    rating: 91,
    players: 40000,
    playersLabel: '~40K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'medium',
    mp: true,
    beginner: true,
    gem: false,
    featured: true,
    trending: true,
    year: 2021,
    universeId: 6929793882,
    placeId: 6929793882,
    modes: ['Solos', 'Duos', 'Squads', 'Teams of 4'],
  },
  {
    id: 'criminality',
    title: 'Criminality',
    creator: '16FLIP',
    genre: 'fps',
    emoji: '🌃',
    desc: 'Gritty street-level FPS set in a criminal underworld with realistic weapon handling, an open city, and emergent player encounters.',
    fullDesc: 'Criminality creates an open-world street crime atmosphere unlike any other Roblox FPS. The weapon handling feels weighty and deliberate. The city map is dense with alleys, rooftops, and interiors. Emergent PvP moments feel genuinely dangerous. It\'s rough around the edges but offers experiences you won\'t find in more polished games.',
    tags: ['Open World', 'Crime', 'Realistic', 'Emergent'],
    rating: 85,
    players: 6000,
    playersLabel: '~6K active',
    badge: 'hidden-gem',
    badgeText: '💎 Hidden Gem',
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: true,
    featured: false,
    trending: false,
    year: 2020,
    universeId: null,
    placeId: null,
    modes: ['Open World PvP'],
  },

  /* ── ADVENTURE ─────────────────────────────── */
  {
    id: 'deepwoken',
    title: 'Deepwoken',
    creator: 'Monad Studios',
    genre: 'adventure',
    emoji: '⚔️',
    desc: 'Hardcore action-RPG with permadeath, deep lore, and skill-based combat. Roblox\'s most ambitious title — punishing, rewarding, and unforgettable.',
    fullDesc: 'Deepwoken is a masterwork of Roblox game design. A fully realized action-RPG with permadeath, a deep skill-tree system, meaningful choices that shape your build, and lore that rewards exploration. Combat is fast and reads like a proper action game. Death means losing everything — which makes every moment tense. Not for the faint-hearted, but absolutely worth it.',
    tags: ['RPG', 'Permadeath', 'Lore', 'Skill-Based', 'Hard'],
    rating: 95,
    players: 20000,
    playersLabel: '~20K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'extreme',
    mp: true,
    beginner: false,
    gem: false,
    featured: true,
    trending: true,
    year: 2021,
    universeId: 4111023553,
    placeId: 4111023553,
    modes: ['Open World', 'PvP', 'PvE'],
  },
  {
    id: 'arcane-odyssey',
    title: 'Arcane Odyssey',
    creator: 'vetexgames',
    genre: 'adventure',
    emoji: '🌊',
    desc: 'Naval exploration RPG with a deep magic system and a handcrafted archipelago. Years in development, exceptional world-building.',
    fullDesc: 'Arcane Odyssey is the result of years of development by vetexgames. A seafaring open-world RPG where you sail between islands, discover secrets, battle rivals, and master a magic system with dozens of elements that can combine. The world feels genuinely lived-in, and the main quest is one of the best Roblox stories ever told.',
    tags: ['Naval', 'Magic', 'Open World', 'RPG', 'Story'],
    rating: 93,
    players: 18000,
    playersLabel: '~18K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'hard',
    mp: true,
    beginner: false,
    gem: false,
    featured: true,
    trending: true,
    year: 2023,
    universeId: 2491889523,
    placeId: 2491889523,
    modes: ['Open World', 'Story', 'PvP'],
  },
  {
    id: 'a-dusty-trip',
    title: 'A Dusty Trip',
    creator: 'AbsintheNoir',
    genre: 'adventure',
    emoji: '🚗',
    desc: 'Drive across a vast post-apocalyptic wasteland, scavenge for fuel, and survive. Atmospheric, open-ended, and genuinely tense.',
    fullDesc: 'A Dusty Trip puts you on a highway through a scorched wasteland. Your job: keep the car running, scavenge supplies from abandoned sites, and survive to the end. The atmosphere is thick, the pacing is deliberate, and the resource management creates real tension. It\'s one of the best recent Roblox releases.',
    tags: ['Survival', 'Open World', 'Scavenging', 'Atmospheric'],
    rating: 91,
    players: 25000,
    playersLabel: '~25K active',
    badge: 'new',
    badgeText: '🆕 Trending',
    diff: 'medium',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: true,
    year: 2024,
    universeId: null,
    placeId: null,
    modes: ['Co-op Survival'],
  },
  {
    id: 'blox-fruits',
    title: 'Blox Fruits',
    creator: 'go play blox fruits',
    genre: 'adventure',
    emoji: '🍎',
    desc: 'One Piece-inspired open world combat RPG. Hunt Devil Fruits, fight bosses, and master combat styles across the seas.',
    fullDesc: 'Blox Fruits translates the One Piece world into a Roblox RPG. Dozens of Devil Fruits each transform your combat style. Three seas to explore with scaling difficulty. Regular updates add new islands, bosses, and fruits. The grind is real but manageable, and the combat variety keeps it fresh.',
    tags: ['RPG', 'Anime', 'Open World', 'Grinding'],
    rating: 85,
    players: 80000,
    playersLabel: '~80K active',
    badge: null,
    diff: 'medium',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2019,
    universeId: 2753915549,
    placeId: 2753915549,
    modes: ['Open World', 'PvP', 'PvE'],
  },
  {
    id: 'world-zero',
    title: 'World // Zero',
    creator: 'RedManta',
    genre: 'adventure',
    emoji: '🌍',
    desc: 'A full MMORPG inside Roblox — dungeons, raids, crafting, guilds. One of the most feature-complete games on the platform.',
    fullDesc: 'World // Zero is proof that you can build a full MMORPG in Roblox. It has everything: dungeon runs, guild systems, skill trees, crafting, a player market, seasonal events, and ongoing content updates. The class system is deep, the combat is satisfying, and there\'s always something to work toward.',
    tags: ['MMORPG', 'Dungeons', 'Guilds', 'Crafting', 'Raids'],
    rating: 89,
    players: 7000,
    playersLabel: '~7K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: false,
    year: 2019,
    universeId: 3579752591,
    placeId: 3579752591,
    modes: ['Co-op Dungeons', 'PvP', 'Raids'],
  },
  {
    id: 'vesteria',
    title: 'Vesteria',
    creator: 'berezaa games',
    genre: 'adventure',
    emoji: '🏹',
    desc: 'A classic fantasy MMORPG with three distinct classes, quests, raids, and a player economy. Built with genuine RPG philosophy.',
    fullDesc: 'Vesteria was one of the first Roblox games to go through a paid alpha — a sign of its quality. Three classes (Warrior, Mage, Hunter) each with branching subclasses, a full quest system, instanced dungeons, and a player-driven economy. It feels like a proper old-school MMORPG.',
    tags: ['MMORPG', 'Fantasy', 'Classes', 'Quests'],
    rating: 88,
    players: 4000,
    playersLabel: '~4K active',
    badge: null,
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: false,
    year: 2019,
    universeId: 1171898769,
    placeId: 1171898769,
    modes: ['Co-op', 'PvE', 'Economy'],
  },
  {
    id: 'project-slayers',
    title: 'Project Slayers',
    creator: 'Xan Studios',
    genre: 'adventure',
    emoji: '🔥',
    desc: 'Demon Slayer-inspired action RPG with an extensive breathing system, clans, and a full demon/slayer questline.',
    fullDesc: 'Project Slayers captures the Demon Slayer anime experience better than any other Roblox game. You can be a Slayer mastering Breathing Styles or a Demon mastering Blood Art abilities. The combat is stylish and skill-based, the world is expansive, and the customization options are deep.',
    tags: ['Anime', 'RPG', 'Demon Slayer', 'Combat'],
    rating: 87,
    players: 15000,
    playersLabel: '~15K active',
    badge: null,
    diff: 'hard',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: false,
    year: 2022,
    universeId: null,
    placeId: null,
    modes: ['Open World', 'PvP', 'PvE'],
  },
  {
    id: 'the-wild-west',
    title: 'The Wild West',
    creator: 'Widgeon',
    genre: 'adventure',
    emoji: '🤠',
    desc: 'Open world cowboy simulation — mining, bounty hunting, horse riding, saloons, and a living player economy in the Old West.',
    fullDesc: 'The Wild West builds a surprisingly authentic frontier experience. You can be a miner, a rancher, a lawman, or an outlaw. The economy runs on player activity. Horses have real physics. Shootouts in town are genuinely exciting. This is one of Roblox\'s most underrated open-world games.',
    tags: ['Open World', 'Western', 'Economy', 'Roleplay'],
    rating: 86,
    players: 10000,
    playersLabel: '~10K active',
    badge: 'hidden-gem',
    badgeText: '💎 Hidden Gem',
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: true,
    featured: false,
    trending: false,
    year: 2019,
    universeId: 3713524179,
    placeId: 3713524179,
    modes: ['Open World', 'PvP', 'Economy'],
  },
  {
    id: 'kaiju-universe',
    title: 'Kaiju Universe',
    creator: 'Godzilla Fan Club',
    genre: 'adventure',
    emoji: '🦖',
    desc: 'Stomp cities as iconic kaiju monsters, level up your creature, and battle other giant beasts. Unique concept with exceptional model quality.',
    fullDesc: 'Kaiju Universe lets you live out the Godzilla fantasy. Control massive monsters with unique abilities, destroy cities, and fight other players or AI kaiju. The models are impressively detailed, the destruction physics are satisfying, and leveling up reveals new abilities. A genuinely original Roblox concept.',
    tags: ['Kaiju', 'Destruction', 'PvP', 'Leveling'],
    rating: 87,
    players: 10000,
    playersLabel: '~10K active',
    badge: null,
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2020,
    universeId: 2713854779,
    placeId: 2713854779,
    modes: ['Open World PvP', 'PvE'],
  },
  {
    id: 'swordburst-2',
    title: 'Swordburst 2',
    creator: 'AbstractAlex',
    genre: 'adventure',
    emoji: '🗡️',
    desc: 'Sword Art Online-inspired dungeon RPG. Clear floors, craft gear, and explore procedural dungeons with a full party system.',
    fullDesc: 'Swordburst 2 faithfully translates the SAO tower-clearing concept. Each floor has unique enemies, bosses, and floor mechanics. Gear crafting is deep, parties are rewarded, and solo play is challenging but possible. It\'s one of Roblox\'s oldest quality RPGs and still holds up.',
    tags: ['SAO', 'Dungeon', 'Crafting', 'Party'],
    rating: 84,
    players: 5000,
    playersLabel: '~5K active',
    badge: 'hidden-gem',
    badgeText: '💎 Hidden Gem',
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: true,
    featured: false,
    trending: false,
    year: 2017,
    universeId: null,
    placeId: null,
    modes: ['Dungeon Co-op', 'PvP'],
  },

  /* ── ROLEPLAY ──────────────────────────────── */
  {
    id: 'jailbreak',
    title: 'Jailbreak',
    creator: 'Badimo',
    genre: 'roleplay',
    emoji: '🚔',
    desc: 'The definitive cops vs criminals experience. Rob banks, escape prison, buy vehicles, and outrun or outthink the police.',
    fullDesc: 'Jailbreak defined an era of Roblox. Rob the bank, jewelry store, or museum. Buy increasingly fast vehicles. Stage prison breaks. Or play as police and prevent it all. The constant cat-and-mouse dynamic means no two sessions are the same. Regular updates add new locations, vehicles, and heists.',
    tags: ['Cops & Robbers', 'Open World', 'Vehicles', 'Heist'],
    rating: 90,
    players: 40000,
    playersLabel: '~40K active',
    badge: 'classic',
    badgeText: '🏛 Classic',
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: true,
    trending: false,
    year: 2017,
    universeId: 606849621,
    placeId: 606849621,
    modes: ['Criminal vs Police', 'Open World'],
  },
  {
    id: 'erlc',
    title: 'Emergency Response: Liberty County',
    creator: 'Polaroid Studios',
    genre: 'roleplay',
    emoji: '🚓',
    desc: 'Play as police, fire, EMS, or civilian in a detailed open world with structured roleplay mechanics.',
    fullDesc: 'ER:LC is serious roleplay done right. Police can issue citations, pull over vehicles, and conduct investigations. Fire and EMS respond to actual incidents. Civilians drive, shop, and cause trouble. The server management tools mean most sessions are organized and drama-free. The best structured roleplay game on Roblox.',
    tags: ['Emergency Services', 'Serious RP', 'Jobs', 'Community'],
    rating: 91,
    players: 20000,
    playersLabel: '~20K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2019,
    universeId: 2534724415,
    placeId: 2534724415,
    modes: ['Structured RP', 'Patrol', 'Events'],
  },
  {
    id: 'work-pizza',
    title: 'Work at a Pizza Place',
    creator: 'Dued1',
    genre: 'roleplay',
    emoji: '🍕',
    desc: 'The original Roblox social simulator done right — take orders, cook, deliver, and earn money to build your house.',
    fullDesc: 'Work at a Pizza Place is one of the oldest and most loved Roblox games for good reason. Every player takes a job — cook, cashier, delivery, or manager — and works together to keep the pizzeria running. Your earnings go toward upgrading your house. Simple, social, satisfying.',
    tags: ['Work', 'Classic', 'Social', 'Cooperative'],
    rating: 88,
    players: 15000,
    playersLabel: '~15K active',
    badge: 'classic',
    badgeText: '🏛 Classic',
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2008,
    universeId: 13058,
    placeId: 13058,
    modes: ['Co-op Work', 'Social'],
  },
  {
    id: 'greenville',
    title: 'Greenville',
    creator: 'Greenville WI',
    genre: 'roleplay',
    emoji: '🌆',
    desc: 'Detailed suburban American town roleplay with realistic vehicles, a working police force, and a player economy.',
    fullDesc: 'Greenville is the most polished small-town roleplay game on Roblox. The vehicle physics are excellent, the town layout feels realistic, and regular updates add new buildings and cars. The roleplay is casual rather than strict — a good middle ground between chaos and structure.',
    tags: ['Town RP', 'Vehicles', 'Economy', 'Casual'],
    rating: 86,
    players: 10000,
    playersLabel: '~10K active',
    badge: null,
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2018,
    universeId: null,
    placeId: null,
    modes: ['Open World RP'],
  },
  {
    id: 'brookhaven',
    title: 'Brookhaven RP',
    creator: 'Wolfpaq',
    genre: 'roleplay',
    emoji: '🏘️',
    desc: 'Relaxed open-world roleplay with housing, vehicles, jobs, and creative storytelling. The most popular RP game on Roblox.',
    fullDesc: 'Brookhaven offers a no-pressure creative sandbox. Claim a house, pick a car, find a job, or just hang out. The game\'s popularity stems from its accessibility and the freedom it gives players to create their own stories. Not for competitive play — purely social and creative.',
    tags: ['Town RP', 'Housing', 'Social', 'Creative'],
    rating: 82,
    players: 90000,
    playersLabel: '~90K active',
    badge: null,
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2020,
    universeId: 4924922222,
    placeId: 4924922222,
    modes: ['Open World RP', 'Social'],
  },

  /* ── HORROR ────────────────────────────────── */
  {
    id: 'doors',
    title: 'Doors',
    creator: 'LSPLASH',
    genre: 'horror',
    emoji: '🚪',
    desc: 'Navigate procedurally generated rooms while avoiding terrifying entities. Each door brings new dread — the horror design is genuinely clever.',
    fullDesc: 'Doors is the benchmark horror game on Roblox. Each run generates new room layouts, entity behaviors, and item placements. The monsters — Rush, Ambush, Screech, and more — each have unique mechanics that you must learn. The atmosphere is oppressive without being cheap. Hotel+ DLC expanded the experience significantly.',
    tags: ['Procedural', 'Entities', 'Co-op', 'Survival Horror'],
    rating: 96,
    players: 35000,
    playersLabel: '~35K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: false,
    featured: true,
    trending: true,
    year: 2022,
    universeId: 1534453647,
    placeId: 1534453647,
    modes: ['Hotel', 'Hotel+ (DLC)'],
  },
  {
    id: 'the-mimic',
    title: 'The Mimic',
    creator: 'MUCDICH',
    genre: 'horror',
    emoji: '👹',
    desc: 'Japanese folklore horror with multi-chapter storytelling. Atmospheric, disturbing, and story-focused — not just jumpscare bait.',
    fullDesc: 'The Mimic draws from Japanese mythology and folklore — Oni, Kuchisake-onna, and other spirits form the basis of its four-chapter horror experience. Each chapter has a distinct story, unique monster behavior, and escalating dread. The atmosphere is exceptional, and the lore rewards players who pay attention.',
    tags: ['Japanese Folklore', 'Story', 'Atmospheric', 'Chapters'],
    rating: 92,
    players: 12000,
    playersLabel: '~12K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: false,
    year: 2021,
    universeId: 7355322558,
    placeId: 7355322558,
    modes: ['Chapter 1', 'Chapter 2', 'Chapter 3', 'Chapter 4'],
  },
  {
    id: 'apeirophobia',
    title: 'Apeirophobia',
    creator: 'Polaroid Studios',
    genre: 'horror',
    emoji: '🌀',
    desc: 'Escape the Backrooms through layered liminal environments. High production value, atmospheric dread, creative puzzle mechanics.',
    fullDesc: 'Apeirophobia uses the Backrooms concept as a launchpad for genuinely creative horror design. Each level has a unique aesthetic — from fluorescent office corridors to underwater facilities. The puzzles are clever, the entities are dangerous, and the pacing keeps you tense throughout.',
    tags: ['Backrooms', 'Liminal', 'Puzzle', 'Atmospheric'],
    rating: 90,
    players: 8000,
    playersLabel: '~8K active',
    badge: null,
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: false,
    year: 2022,
    universeId: 9508087919,
    placeId: 9508087919,
    modes: ['Linear Escape'],
  },
  {
    id: 'piggy',
    title: 'Piggy',
    creator: 'MiniToon',
    genre: 'horror',
    emoji: '🐷',
    desc: 'Escape maps while one player hunts as Piggy. Story-driven with chapters, lore, and puzzle mechanics beyond just running.',
    fullDesc: 'Piggy started as a Peppa Pig horror meme and grew into a legitimate multi-chapter story game. Over a dozen chapters each with unique maps, characters, and puzzle designs. The lore goes surprisingly deep, and the community has stayed engaged throughout regular updates.',
    tags: ['Story', 'Escape', 'Chapter-Based', 'Puzzle'],
    rating: 87,
    players: 15000,
    playersLabel: '~15K active',
    badge: 'classic',
    badgeText: '🏛 Classic',
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2020,
    universeId: 4836741756,
    placeId: 4836741756,
    modes: ['Story', 'Build Mode', 'Custom Maps'],
  },
  {
    id: '3008',
    title: '3008',
    creator: 'uglyburger0',
    genre: 'horror',
    emoji: '🏪',
    desc: 'Survive inside an infinite IKEA-like store. Scavenge food, build shelter, and avoid the mannequins that come alive at night.',
    fullDesc: 'Based on the SCP-3008 creepypasta, this game drops you in a seemingly endless IKEA-inspired furniture store. By day, scavenge furniture, food, and supplies. At night, the mannequins animate and hunt. The survival loop is deeply compelling, and the multiplayer creates emergent stories.',
    tags: ['Survival', 'SCP', 'Infinite Store', 'Day-Night Cycle'],
    rating: 89,
    players: 15000,
    playersLabel: '~15K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: true,
    year: 2021,
    universeId: null,
    placeId: null,
    modes: ['Survival', 'Co-op'],
  },
  {
    id: 'dead-silence',
    title: 'Dead Silence',
    creator: 'DoomX10',
    genre: 'horror',
    emoji: '🎭',
    desc: 'Based on the horror film — navigate a haunted theatre and uncover the story of Mary Shaw while avoiding her deadly puppets.',
    fullDesc: 'Dead Silence recreates the atmosphere of the 2007 horror film with surprising fidelity. The theatre is deeply unsettling, the puppet designs are genuinely creepy, and the sound design elevates everything. More of a walking-horror experience than an action game, but the tension is real.',
    tags: ['Film-Based', 'Puppets', 'Story', 'Atmospheric'],
    rating: 85,
    players: 4000,
    playersLabel: '~4K active',
    badge: 'hidden-gem',
    badgeText: '💎 Hidden Gem',
    diff: 'hard',
    mp: true,
    beginner: false,
    gem: true,
    featured: false,
    trending: false,
    year: 2018,
    universeId: null,
    placeId: null,
    modes: ['Story Horror'],
  },

  /* ── TYCOON ────────────────────────────────── */
  {
    id: 'theme-park-tycoon-2',
    title: 'Theme Park Tycoon 2',
    creator: 'Den_S',
    genre: 'tycoon',
    emoji: '🎢',
    desc: 'Build and manage your own theme park with real coaster building tools. The creative depth is extraordinary.',
    fullDesc: 'Theme Park Tycoon 2 is a genuine sandbox management game. The roller coaster builder lets you design tracks with full 3D freedom. Guest AI responds realistically to your park design. Players have recreated real-world parks like Disney and Universal inside this game — the depth is extraordinary.',
    tags: ['Building', 'Creative', 'Management', 'Coasters'],
    rating: 96,
    players: 12000,
    playersLabel: '~12K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'easy',
    mp: false,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2014,
    universeId: 69184822,
    placeId: 69184822,
    modes: ['Solo Build', 'Multiplayer Park'],
  },
  {
    id: 'retail-tycoon-2',
    title: 'Retail Tycoon 2',
    creator: 'Widgeon',
    genre: 'tycoon',
    emoji: '🏪',
    desc: 'Build and run a supermarket with real restocking, employee management, and product pricing. Genuinely deep business sim.',
    fullDesc: 'Retail Tycoon 2 goes far beyond most tycoon games. Manage inventory, set product prices, hire staff, design store layouts, and compete with other players. The economic simulation is deep enough to be genuinely interesting, and the building tools let you create exactly the store you envision.',
    tags: ['Business', 'Management', 'Economy', 'Building'],
    rating: 88,
    players: 6000,
    playersLabel: '~6K active',
    badge: null,
    diff: 'medium',
    mp: false,
    beginner: false,
    gem: false,
    featured: false,
    trending: false,
    year: 2019,
    universeId: 2767204726,
    placeId: 2767204726,
    modes: ['Solo', 'Multiplayer'],
  },
  {
    id: 'build-a-boat',
    title: 'Build a Boat for Treasure',
    creator: 'Chillz Studios',
    genre: 'tycoon',
    emoji: '⛵',
    desc: 'Build your own boat then sail it through obstacles. Physics-based with satisfying destruction when things go wrong.',
    fullDesc: 'Build a Boat is creativity meets physics chaos. You design a vehicle, then watch it attempt a chaotic obstacle course filled with water, fans, and explosions. Learning how to build something that actually survives the course is a satisfying engineering puzzle.',
    tags: ['Physics', 'Building', 'Obstacles', 'Creative'],
    rating: 87,
    players: 20000,
    playersLabel: '~20K active',
    badge: 'classic',
    badgeText: '🏛 Classic',
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2016,
    universeId: 537413528,
    placeId: 537413528,
    modes: ['Build & Race'],
  },
  {
    id: 'restaurant-tycoon-2',
    title: 'Restaurant Tycoon 2',
    creator: 'Ultraw',
    genre: 'tycoon',
    emoji: '🍽️',
    desc: 'Design your restaurant, manage supply chains, hire staff, and grow from a food stall to a five-star establishment.',
    fullDesc: 'Restaurant Tycoon 2 covers the full arc of running a restaurant. Start with a basic menu and simple decor, scale up through customer feedback, manage suppliers, hire waiters, chefs, and hosts. The decoration system is detailed enough to create genuinely beautiful spaces.',
    tags: ['Restaurant', 'Decoration', 'Staff', 'Management'],
    rating: 85,
    players: 8000,
    playersLabel: '~8K active',
    badge: null,
    diff: 'easy',
    mp: false,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2018,
    universeId: 2161219674,
    placeId: 2161219674,
    modes: ['Solo', 'Co-op'],
  },

  /* ── PLATFORMER ────────────────────────────── */
  {
    id: 'tower-of-hell',
    title: 'Tower of Hell',
    creator: 'YXceptional Studios',
    genre: 'platformer',
    emoji: '🗼',
    desc: 'Race to the top of a procedurally assembled tower with no checkpoints. Pure platforming skill — nothing to buy, everything to earn.',
    fullDesc: 'Tower of Hell is the ultimate platforming purity test. Six random sections stack into a tower, no checkpoints, first to the top wins. The sections rotate and cycle constantly, so the tower is always different. Your skill ceiling rises the more you play — and it keeps rising.',
    tags: ['Obby', 'Competitive', 'No Checkpoints', 'Skill'],
    rating: 92,
    players: 40000,
    playersLabel: '~40K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'hard',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: false,
    year: 2018,
    universeId: 1962086868,
    placeId: 1962086868,
    modes: ['Race', 'Practice'],
  },
  {
    id: 'flood-escape-2',
    title: 'Flood Escape 2',
    creator: 'Crazyblox Games',
    genre: 'platformer',
    emoji: '💧',
    desc: 'Cooperatively escape rising floodwater through beautifully designed maps. Demanding, progression based entirely on skill.',
    fullDesc: 'Flood Escape 2 is cooperative platforming at its finest. Players race through intricately designed maps as water rises from below. The maps are gorgeous, the difficulty scales from Beginner to Insane, and the time pressure creates intense moments. Community maps mean there\'s always new content.',
    tags: ['Co-op', 'Escape', 'Skill', 'Rising Water'],
    rating: 93,
    players: 8000,
    playersLabel: '~8K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'hard',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: false,
    year: 2017,
    universeId: 738689294,
    placeId: 738689294,
    modes: ['Campaign', 'Custom Maps'],
  },
  {
    id: 'speed-run-4',
    title: 'Speed Run 4',
    creator: 'Vurse',
    genre: 'platformer',
    emoji: '⚡',
    desc: 'One of Roblox\'s oldest beloved platformers. 30 unique levels of pure running and jumping. A true classic.',
    fullDesc: 'Speed Run 4 was one of Roblox\'s first quality platformers and still holds up beautifully. Thirty distinct levels, each with a unique theme and obstacle set. No gimmicks, no power-ups — just your timing and movement. A must-play for any platformer fan.',
    tags: ['Classic', 'Levels', 'Pure Platforming'],
    rating: 85,
    players: 6000,
    playersLabel: '~6K active',
    badge: 'classic',
    badgeText: '🏛 Classic',
    diff: 'medium',
    mp: false,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2010,
    universeId: 175181,
    placeId: 175181,
    modes: ['Solo', 'Race'],
  },
  {
    id: 'a-universal-time',
    title: 'A Universal Time',
    creator: 'Universe Time Studio',
    genre: 'platformer',
    emoji: '🌟',
    desc: 'Anime-inspired fighting game with Stands, abilities, and a deep PvP meta.',
    fullDesc: 'A Universal Time draws from JoJo\'s Bizarre Adventure and other anime to create a roster of unique Stands and abilities. The combat system is deep, with each ability having counters and combos. The meta constantly evolves as the developer balances and adds new Stands.',
    tags: ['Anime', 'Fighting', 'Stands', 'PvP Meta'],
    rating: 86,
    players: 12000,
    playersLabel: '~12K active',
    badge: null,
    diff: 'hard',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: false,
    year: 2020,
    universeId: 2820819809,
    placeId: 2820819809,
    modes: ['PvP', 'Story', 'Grinding'],
  },
  {
    id: 'escape-room',
    title: 'Escape Room',
    creator: 'devzeb',
    genre: 'platformer',
    emoji: '🔐',
    desc: 'Logic-based puzzle escape rooms with genuinely clever mechanics. Pure brain power — a refreshing change of pace.',
    fullDesc: 'Escape Room on Roblox is one of the few genuinely puzzle-focused experiences. Each room requires actual logical thinking — reading clues, connecting patterns, and deducing combinations. No combat, no time pressure — just the satisfaction of solving something clever.',
    tags: ['Puzzle', 'Logic', 'Brain Teaser', 'Relaxing'],
    rating: 84,
    players: 5000,
    playersLabel: '~5K active',
    badge: 'hidden-gem',
    badgeText: '💎 Hidden Gem',
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: true,
    featured: false,
    trending: false,
    year: 2016,
    universeId: null,
    placeId: null,
    modes: ['Co-op Puzzle'],
  },

  /* ── SOCIAL ────────────────────────────────── */
  {
    id: 'murder-mystery-2',
    title: 'Murder Mystery 2',
    creator: 'Nikilis',
    genre: 'social',
    emoji: '🔪',
    desc: 'One murderer, one sheriff, everyone else is innocent. Social deduction with excellent cosmetics and a tense formula.',
    fullDesc: 'Murder Mystery 2 is one of Roblox\'s most enduring social games. The formula is tight: one player gets a knife, one gets a gun, everyone else must survive or deduce who the murderer is. Hundreds of weapon and pet cosmetics give players long-term goals, but none of them affect gameplay.',
    tags: ['Deduction', 'Social', 'Cosmetics', 'Replayable'],
    rating: 88,
    players: 30000,
    playersLabel: '~30K active',
    badge: 'classic',
    badgeText: '🏛 Classic',
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2014,
    universeId: 142823291,
    placeId: 142823291,
    modes: ['Classic', 'Hardcore'],
  },
  {
    id: 'natural-disaster-survival',
    title: 'Natural Disaster Survival',
    creator: 'Stickmasterluke',
    genre: 'social',
    emoji: '🌪️',
    desc: 'Survive earthquakes, floods, and hurricanes with dozens of players. A pure Roblox classic with genuinely chaotic fun.',
    fullDesc: 'Natural Disaster Survival is one of the oldest Roblox games that still holds up perfectly. Each round, a different disaster strikes — tornado, earthquake, flood, meteor shower — and everyone scrambles to survive. The chaos is endlessly fun, and the random disasters keep every round fresh.',
    tags: ['Survival', 'Classic', 'Party', 'Chaos'],
    rating: 85,
    players: 20000,
    playersLabel: '~20K active',
    badge: 'classic',
    badgeText: '🏛 Classic',
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2008,
    universeId: 19697,
    placeId: 19697,
    modes: ['Classic', 'Random Disasters'],
  },
  {
    id: 'funky-friday',
    title: 'Funky Friday',
    creator: 'Labile Group',
    genre: 'social',
    emoji: '🎵',
    desc: 'Friday Night Funkin\' inspired rhythm game with a huge custom song library. Pure music — no pay-to-win, just hit the arrows.',
    fullDesc: 'Funky Friday delivers a compelling rhythm game experience directly inspired by Friday Night Funkin\'. The note charts are tight, the custom song library is enormous, and the 1v1 competitive format adds stakes to every performance. No monetization that affects gameplay.',
    tags: ['Rhythm', 'Music', 'FNF', 'Competitive'],
    rating: 91,
    players: 25000,
    playersLabel: '~25K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'medium',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2021,
    universeId: 6872265039,
    placeId: 6872265039,
    modes: ['1v1', 'Story', 'Free Play'],
  },
  {
    id: 'evade',
    title: 'Evade',
    creator: 'Hexagon Development',
    genre: 'social',
    emoji: '🏃',
    desc: 'Evade AI entities with friends across varied maps. Smooth movement, great visuals, and genuinely terrifying chases.',
    fullDesc: 'Evade is a run-and-dodge game with serious production quality. AI entities chase players across maps while you\'re trying to complete objectives or simply survive. The character movement is smooth and expressive, the maps are well-designed, and the multiplayer chaos is brilliant.',
    tags: ['Co-op', 'Evading', 'Chase', 'Party'],
    rating: 88,
    players: 20000,
    playersLabel: '~20K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: true,
    year: 2022,
    universeId: null,
    placeId: null,
    modes: ['Classic', 'Infected', 'Custom'],
  },
  {
    id: 'survive-the-disasters-2',
    title: 'Survive the Disasters 2',
    creator: 'vyrissOW',
    genre: 'social',
    emoji: '☄️',
    desc: 'Vote on disasters, then frantically survive them. More chaotic and varied than Natural Disaster Survival with 200+ disaster types.',
    fullDesc: 'Survive the Disasters 2 takes the Natural Disaster Survival concept and amplifies it tenfold. 200+ disasters ranging from realistic (tornado, flood) to absurd (giant NPCs, laser grids). Players vote on what happens next, creating memorable and hilarious moments.',
    tags: ['Chaos', 'Disasters', 'Party', 'Voting'],
    rating: 86,
    players: 8000,
    playersLabel: '~8K active',
    badge: 'hidden-gem',
    badgeText: '💎 Hidden Gem',
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: true,
    featured: false,
    trending: false,
    year: 2017,
    universeId: null,
    placeId: null,
    modes: ['Classic', 'Voting'],
  },
  {
    id: 'epic-minigames',
    title: 'Epic Minigames',
    creator: 'Alexnewtron',
    genre: 'social',
    emoji: '🎲',
    desc: 'Hundreds of diverse minigames with constantly rotating gameplay. Always fair, always different.',
    fullDesc: 'Epic Minigames has accumulated hundreds of minigames over the years — from obstacle courses to team battles to trivia. The rotating format means you\'re rarely playing the same thing twice, and the sheer variety keeps groups entertained indefinitely.',
    tags: ['Minigames', 'Party', 'Variety', 'Classic'],
    rating: 84,
    players: 15000,
    playersLabel: '~15K active',
    badge: null,
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2014,
    universeId: null,
    placeId: null,
    modes: ['Classic Rotation'],
  },

  /* ── STRATEGY ──────────────────────────────── */
  {
    id: 'tower-defense-simulator',
    title: 'Tower Defense Simulator',
    creator: 'Paradoxum Games',
    genre: 'strategy',
    emoji: '🏰',
    desc: 'Cooperatively defend against increasingly difficult waves. Genuine strategy with dozens of tower types and maps.',
    fullDesc: 'Tower Defense Simulator is the pinnacle of Roblox tower defense. Dozens of towers — each with upgrades and unique mechanics — cooperate to defend against waves of enemies. Harder difficulties require genuine coordination and knowledge of tower synergies. Regular seasonal events add limited towers and maps.',
    tags: ['Tower Defense', 'Co-op', 'Strategy', 'Waves'],
    rating: 91,
    players: 18000,
    playersLabel: '~18K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: false,
    year: 2019,
    universeId: 3260590327,
    placeId: 3260590327,
    modes: ['Co-op', 'Solo', 'Hardcore'],
  },
  {
    id: 'booga-booga',
    title: 'Booga Booga',
    creator: 'soybeen',
    genre: 'strategy',
    emoji: '⛏️',
    desc: 'Survival crafting on floating islands with tribal warfare, base building, and resource competition.',
    fullDesc: 'Booga Booga is one of Roblox\'s best survival sandbox games. Mine resources on floating islands, craft weapons and tools, build your base, and compete with other tribes for territory. The resource loop is satisfying, and the tribal warfare creates memorable emergent stories.',
    tags: ['Survival', 'Crafting', 'PvP', 'Tribe Warfare'],
    rating: 87,
    players: 6000,
    playersLabel: '~6K active',
    badge: 'classic',
    badgeText: '🏛 Classic',
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: false,
    year: 2018,
    universeId: 1323567932,
    placeId: 1323567932,
    modes: ['Open World', 'PvP', 'PvE'],
  },
  {
    id: 'islands',
    title: 'Islands',
    creator: 'Easy.gg',
    genre: 'strategy',
    emoji: '🏝️',
    desc: 'Build your island, farm resources, craft machines, and trade with other players. One of Roblox\'s most satisfying progression games.',
    fullDesc: 'Islands is a Stardew Valley-meets-Minecraft sandbox. Your floating island can be shaped, built on, and automated with crafting machines. Resource gathering leads to more complex machines, which leads to more resources — a compelling loop. The multiplayer trading economy adds depth.',
    tags: ['Building', 'Economy', 'Farming', 'Automation'],
    rating: 88,
    players: 10000,
    playersLabel: '~10K active',
    badge: null,
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2020,
    universeId: null,
    placeId: null,
    modes: ['Solo', 'Co-op', 'Trading'],
  },
  {
    id: 'phantom-armies',
    title: 'Phantom Armies',
    creator: 'Phosfor',
    genre: 'strategy',
    emoji: '🪖',
    desc: 'Real-time military strategy with troop placement, resource management, and base assault. Deep for a Roblox game.',
    fullDesc: 'Phantom Armies brings RTS mechanics to Roblox rarely seen on the platform. Manage resources, position troops, build defenses, and coordinate attacks against enemy bases. The strategic layer is genuine — poor decisions lose the game, smart play wins it.',
    tags: ['RTS', 'Military', 'Base Building', 'Strategy'],
    rating: 82,
    players: 2000,
    playersLabel: '~2K active',
    badge: 'hidden-gem',
    badgeText: '💎 Hidden Gem',
    diff: 'hard',
    mp: true,
    beginner: false,
    gem: true,
    featured: false,
    trending: false,
    year: 2019,
    universeId: null,
    placeId: null,
    modes: ['1v1', 'Team Battle'],
  },

  /* ── RACING ────────────────────────────────── */
  {
    id: 'vehicle-simulator',
    title: 'Vehicle Simulator',
    creator: 'Simbuilder',
    genre: 'racing',
    emoji: '🚗',
    desc: 'Buy, tune, and race realistic cars across multiple maps. Physics-based driving with a massive vehicle roster and economy.',
    fullDesc: 'Vehicle Simulator is Roblox\'s longest-running car game. Hundreds of real vehicles from economy cars to hypercars, an in-game economy based on racing and jobs, and tuning options that actually affect performance. The driving physics aren\'t perfect but they\'re engaging.',
    tags: ['Cars', 'Physics', 'Tuning', 'Economy'],
    rating: 85,
    players: 12000,
    playersLabel: '~12K active',
    badge: null,
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2016,
    universeId: 42428321,
    placeId: 42428321,
    modes: ['Open World', 'Racing', 'Jobs'],
  },
  {
    id: 'driving-empire',
    title: 'Driving Empire',
    creator: 'Wayfort',
    genre: 'racing',
    emoji: '🏎️',
    desc: 'Open world driving with real car models, a working economy, livery editor, and organized racing events.',
    fullDesc: 'Driving Empire focuses on the social side of car culture. Hundreds of real-world cars with accurate livery editors, organized racing events with leaderboards, and a community economy. If you care about cars and want to show them off, this is the game.',
    tags: ['Open World', 'Cars', 'Events', 'Livery'],
    rating: 87,
    players: 15000,
    playersLabel: '~15K active',
    badge: null,
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2021,
    universeId: null,
    placeId: null,
    modes: ['Open World', 'Races', 'Showroom'],
  },
  {
    id: 'karting-world',
    title: 'Karting World',
    creator: 'Paced',
    genre: 'racing',
    emoji: '🏁',
    desc: 'Mario Kart-inspired kart racing with items, power-ups, and tight circuits. Chaotic and great with friends.',
    fullDesc: 'Karting World nails the Mario Kart formula in Roblox. Circuit racing with items — blue shells, missiles, boosts — creates the same frantic, comeback-heavy experience as the original. The tracks are well-designed, the item balance is decent, and multiplayer is a blast.',
    tags: ['Karts', 'Items', 'Party', 'Circuits'],
    rating: 84,
    players: 6000,
    playersLabel: '~6K active',
    badge: 'hidden-gem',
    badgeText: '💎 Hidden Gem',
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: true,
    featured: false,
    trending: false,
    year: 2022,
    universeId: null,
    placeId: null,
    modes: ['Race', 'Battle'],
  },

  /* ── SPORTS ────────────────────────────────── */
  {
    id: 'super-striker-league',
    title: 'Super Striker League',
    creator: 'Super Striker League',
    genre: 'sports',
    emoji: '⚽',
    desc: 'The most complete football/soccer experience on Roblox. Skill-based passing and shooting, custom teams, and competitive leagues.',
    fullDesc: 'Super Striker League is a serious football game. Passing, shooting, and positioning require real skill. Custom team creation, organized leagues, and seasonal tournaments give long-term goals. The game rewards players who actually understand football tactics.',
    tags: ['Football', 'Teams', 'Skill', 'Leagues'],
    rating: 88,
    players: 8000,
    playersLabel: '~8K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'medium',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2018,
    universeId: 1058773439,
    placeId: 1058773439,
    modes: ['Quick Match', 'League', 'Custom'],
  },
  {
    id: 'basketball-legends',
    title: 'Basketball Legends',
    creator: 'Sport Legends Studio',
    genre: 'sports',
    emoji: '🏀',
    desc: 'Skill-based basketball with dribble moves, post play, and ranked matches. Actually resembles real basketball strategy.',
    fullDesc: 'Basketball Legends doesn\'t just require button mashing — the dribble move system rewards practice, post play is a real skill, and understanding spacing and timing separates good players from great ones. The ranked system gives competitive players something to chase.',
    tags: ['Basketball', 'Ranked', 'Skill', 'Dribbling'],
    rating: 84,
    players: 6000,
    playersLabel: '~6K active',
    badge: null,
    diff: 'medium',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2017,
    universeId: null,
    placeId: null,
    modes: ['Quick Match', 'Ranked', 'Tournament'],
  },
  {
    id: 'fencing-duel',
    title: 'Fencing Duel',
    creator: 'Thinker',
    genre: 'sports',
    emoji: '🤺',
    desc: 'Precise, physics-based fencing duels. One of the most mechanically unique sports games on Roblox — timing is everything.',
    fullDesc: 'Fencing Duel models the physics of actual fencing with surprising accuracy. Attacks require proper timing and positioning, ripostes and parries are real mechanics, and matches play out more like chess than button-mashing. A hidden gem for players who want something genuinely different.',
    tags: ['Fencing', '1v1', 'Physics', 'Precise'],
    rating: 82,
    players: 2000,
    playersLabel: '~2K active',
    badge: 'hidden-gem',
    badgeText: '💎 Hidden Gem',
    diff: 'hard',
    mp: true,
    beginner: false,
    gem: true,
    featured: false,
    trending: false,
    year: 2020,
    universeId: null,
    placeId: null,
    modes: ['1v1 Duel'],
  },

  /* ── BUILDING ──────────────────────────────── */
  {
    id: 'lumber-tycoon-2',
    title: 'Lumber Tycoon 2',
    creator: 'Defaultio',
    genre: 'building',
    emoji: '🪵',
    desc: 'Chop trees, haul lumber, buy upgrades, and build freely. One of Roblox\'s most satisfying open-ended progression games.',
    fullDesc: 'Lumber Tycoon 2 is a masterclass in satisfying progression. Chop trees, transport them to the sawmill, sell planks, and reinvest in better saws and trucks. The building system lets you construct anything you want. The seasonal wood types and rare biomes give long-term goals.',
    tags: ['Sandbox', 'Wood', 'Progression', 'Building'],
    rating: 90,
    players: 10000,
    playersLabel: '~10K active',
    badge: 'classic',
    badgeText: '🏛 Classic',
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2013,
    universeId: 13822889,
    placeId: 13822889,
    modes: ['Solo', 'Co-op'],
  },
  {
    id: 'welcome-to-bloxburg',
    title: 'Welcome to Bloxburg',
    creator: 'Coeptus',
    genre: 'building',
    emoji: '🏠',
    desc: 'Build your dream home, work jobs, and live a virtual life. The most polished house-building experience on Roblox.',
    fullDesc: 'Welcome to Bloxburg combines The Sims-style life simulation with a deep house building system. Work jobs to earn money, spend it on land and furniture, and design a home with real architectural tools. The building system is flexible enough that players create genuinely impressive structures.',
    tags: ['Housing', 'Jobs', 'Lifestyle', 'Building'],
    rating: 91,
    players: 50000,
    playersLabel: '~50K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2014,
    universeId: 185655149,
    placeId: 185655149,
    modes: ['Solo', 'Multiplayer', 'Roleplay'],
  },

  /* ── FPS ADDITIONS ─────────────────────────── */
  {
    id: 'combat-warriors',
    title: 'Combat Warriors',
    creator: 'LevelUp Studios',
    genre: 'fps',
    emoji: '⚔️',
    desc: 'Intense melee and gun combat with stylish kills. Skill-based PvP with a cosmetics system that never affects gameplay balance.',
    fullDesc: 'Combat Warriors blends melee brawling with firearms for a unique hybrid combat experience. The game rewards reading opponents, managing positioning, and mastering weapon combos. Regular updates add new maps, weapons, and seasonal cosmetics. Zero pay-to-win — all gameplay advantages are earned through skill.',
    tags: ['Melee', 'Gun Combat', 'PvP', 'Cosmetics'],
    rating: 89,
    players: 22000,
    playersLabel: '~22K active',
    badge: null,
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: true,
    year: 2020,
    universeId: null,
    placeId: null,
    modes: ['Team Deathmatch', 'Free For All', 'Tournaments'],
  },
  {
    id: 'frontlines',
    title: 'Frontlines',
    creator: 'Nexus Studio',
    genre: 'fps',
    emoji: '🪖',
    desc: 'Military FPS with team tactics, vehicle combat, and large-scale battles. Roblox\'s most ambitious war game.',
    fullDesc: 'Frontlines delivers a full military FPS experience — infantry combat, driveable vehicles (jeeps, tanks, helicopters), large maps with objectives, and class-based loadouts. Team communication and coordination are essential for victory. The technical execution is exceptional for a Roblox game.',
    tags: ['Military', 'Vehicles', 'Tactical', 'Class-Based'],
    rating: 88,
    players: 12000,
    playersLabel: '~12K active',
    badge: null,
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: false,
    year: 2022,
    universeId: null,
    placeId: null,
    modes: ['Conquest', 'Team Deathmatch', 'Domination'],
  },

  /* ── ADVENTURE ADDITIONS ────────────────────── */
  {
    id: 'grand-piece-online',
    title: 'Grand Piece Online',
    creator: 'Grand Quest Games',
    genre: 'adventure',
    emoji: '🏴‍☠️',
    desc: 'One Piece-inspired open world with sailing, Devil Fruits, and sea exploration. The most faithful anime RPG on Roblox.',
    fullDesc: 'Grand Piece Online captures the spirit of One Piece with stunning fidelity. Sail between islands, discover powerful Devil Fruits, fight NPCs and players, and build a pirate crew. The world is expansive, the progression is skill-driven, and the sea exploration creates genuinely exciting moments. Regular updates add new islands and fruits.',
    tags: ['Anime', 'One Piece', 'Naval', 'Open World', 'RPG'],
    rating: 91,
    players: 25000,
    playersLabel: '~25K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: false,
    featured: true,
    trending: true,
    year: 2020,
    universeId: 4675948834,
    placeId: 4675948834,
    modes: ['Open World', 'PvP', 'PvE'],
  },
  {
    id: 'type-soul',
    title: 'Type Soul',
    creator: 'Type Soul Team',
    genre: 'adventure',
    emoji: '☠️',
    desc: 'Bleach anime-inspired combat RPG with Hollow and Shinigami paths, deep ability progression, and ranked PvP.',
    fullDesc: 'Type Soul lets you live the Bleach experience — become a Shinigami and master Zanpakuto abilities, or embrace your Hollow nature and develop Resurreccion powers. The combat system is deep, with combo routes and ability synergies that reward mastery. The progression feels meaningful, and PvP has a genuine competitive meta.',
    tags: ['Anime', 'Bleach', 'RPG', 'PvP', 'Combat'],
    rating: 87,
    players: 35000,
    playersLabel: '~35K active',
    badge: 'new',
    badgeText: '🆕 Trending',
    diff: 'hard',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: true,
    year: 2023,
    universeId: null,
    placeId: null,
    modes: ['Open World', 'PvP', 'Faction Wars'],
  },
  {
    id: 'dungeon-quest',
    title: 'Dungeon Quest',
    creator: 'vCaffy',
    genre: 'adventure',
    emoji: '🗝️',
    desc: 'Co-op dungeon crawler with weapon drops, class builds, and increasingly brutal difficulty. One of Roblox\'s best RPGs.',
    fullDesc: 'Dungeon Quest is a polished co-op dungeon crawler. Equip randomly generated gear, build your class around unique abilities, and tackle increasingly difficult dungeons with friends. The loot system keeps runs rewarding, the boss fights are genuinely challenging, and the endgame raids are some of the most demanding content on Roblox.',
    tags: ['Dungeon', 'Loot', 'Co-op', 'Builds', 'Raids'],
    rating: 90,
    players: 18000,
    playersLabel: '~18K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'hard',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: false,
    year: 2018,
    universeId: 2814076842,
    placeId: 2714902960,
    modes: ['Normal', 'Nightmare', 'Insane', 'Nightmare Raids'],
  },
  {
    id: 'peroxide',
    title: 'Peroxide',
    creator: 'Peroxide Team',
    genre: 'adventure',
    emoji: '🌙',
    desc: 'Bleach-inspired open world combat with Quincy, Hollow, and Shinigami factions. Deep build system and live balance patches.',
    fullDesc: 'Peroxide is a newer, more polished Bleach RPG with three playable factions — Shinigami, Hollow, and Quincy — each with unique ability trees. The combat feels responsive and skill-driven, the faction system creates emergent conflict, and the developer actively balances and updates the game.',
    tags: ['Anime', 'Bleach', 'Open World', 'Factions', 'RPG'],
    rating: 86,
    players: 20000,
    playersLabel: '~20K active',
    badge: 'new',
    badgeText: '🆕 Trending',
    diff: 'hard',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: true,
    year: 2023,
    universeId: null,
    placeId: null,
    modes: ['Open World', 'PvP', 'PvE'],
  },
  {
    id: 'shindo-life',
    title: 'Shindo Life',
    creator: 'RELL World',
    genre: 'adventure',
    emoji: '🍃',
    desc: 'Naruto-inspired ninja action RPG with 70+ bloodlines, bijuu fights, and a sprawling ninja world to explore.',
    fullDesc: 'Shindo Life is an expansive Naruto-inspired game with over 70 unique bloodlines, each with distinct abilities and combo routes. The world has dozens of zones, powerful bijuu bosses to defeat, and a deep progression system. Mastering bloodline combinations separates casual players from serious ones.',
    tags: ['Anime', 'Naruto', 'RPG', 'Bloodlines', 'Combat'],
    rating: 84,
    players: 45000,
    playersLabel: '~45K active',
    badge: null,
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: false,
    year: 2019,
    universeId: 4233262879,
    placeId: 4233262879,
    modes: ['Open World', 'PvP', 'PvE'],
  },
  {
    id: 'loomian-legacy',
    title: 'Loomian Legacy',
    creator: 'LLDEV',
    genre: 'adventure',
    emoji: '🐉',
    desc: 'Pokémon-inspired creature collection RPG with a full story campaign, 80+ Loomians to collect, and competitive battles.',
    fullDesc: 'Loomian Legacy is the most polished Pokémon-style game on Roblox. A full story campaign with cutscenes, 80+ unique creatures each with typing and move sets, and a robust competitive battling scene. The developers update it like a real game — balance patches, new Loomians, seasonal events.',
    tags: ['Pokemon', 'Monster Collector', 'RPG', 'Story', 'Competitive'],
    rating: 88,
    players: 12000,
    playersLabel: '~12K active',
    badge: 'quality',
    badgeText: '⭐ Top Pick',
    diff: 'easy',
    mp: false,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2019,
    universeId: 3834544622,
    placeId: 2557472280,
    modes: ['Story', 'Online Battles', 'Trading'],
  },

  /* ── HORROR ADDITIONS ───────────────────────── */
  {
    id: 'pressure',
    title: 'Pressure',
    creator: 'Endo Games',
    genre: 'horror',
    emoji: '🌊',
    desc: 'Underwater horror with terrifying creatures, stealth mechanics, and a tense narrative. A landmark in Roblox horror.',
    fullDesc: 'Pressure sets you in a drowning underwater facility haunted by massive, unique monsters. Each creature behaves differently — some hunt by sound, others by light, some by smell. The level design forces close encounters and perfect decision-making. The atmosphere is oppressive, the creature design is outstanding, and the lore is genuinely captivating.',
    tags: ['Underwater', 'Entities', 'Stealth', 'Atmospheric', 'Story'],
    rating: 94,
    players: 28000,
    playersLabel: '~28K active',
    badge: 'new',
    badgeText: '🆕 Trending',
    diff: 'hard',
    mp: true,
    beginner: false,
    gem: false,
    featured: true,
    trending: true,
    year: 2024,
    universeId: null,
    placeId: null,
    modes: ['Story', 'Co-op', 'Nightmare Mode'],
  },

  /* ── ROLEPLAY ADDITIONS ─────────────────────── */
  {
    id: 'da-hood',
    title: 'Da Hood',
    creator: 'Da Hood Entertainment',
    genre: 'roleplay',
    emoji: '🌆',
    desc: 'Gritty open-world urban survival — rob, evade police, build rep, and navigate a dangerous city with your crew.',
    fullDesc: 'Da Hood creates a tense, emergent urban survival experience. Rob stores, build up cash, watch your back from other players and police, and establish yourself in the neighborhood. The interaction between rival players creates genuinely unpredictable moments. The realism is surprisingly solid for a Roblox game.',
    tags: ['Open World', 'Urban', 'PvP', 'Survival', 'Crime'],
    rating: 83,
    players: 55000,
    playersLabel: '~55K active',
    badge: null,
    diff: 'hard',
    mp: true,
    beginner: false,
    gem: false,
    featured: false,
    trending: false,
    year: 2019,
    universeId: 4693242103,
    placeId: 4693242103,
    modes: ['Open World PvP'],
  },

  /* ── SOCIAL ADDITIONS ───────────────────────── */
  {
    id: 'flicker',
    title: 'Flicker',
    creator: 'MiniToon',
    genre: 'social',
    emoji: '🕯️',
    desc: 'Gothic social deduction — find the killer among the guests before midnight. Voting, betrayal, and gothic atmosphere done right.',
    fullDesc: 'Flicker takes the social deduction genre and wraps it in a gorgeous gothic aesthetic. Players attend a mysterious event and one is secretly the killer. Gather clues, interrogate, vote out suspects, and survive to dawn. The map design is excellent, the role system is clever, and the atmosphere is far superior to most Roblox social games.',
    tags: ['Social Deduction', 'Mystery', 'Gothic', 'Voting', 'Strategy'],
    rating: 87,
    players: 14000,
    playersLabel: '~14K active',
    badge: 'hidden-gem',
    badgeText: '💎 Hidden Gem',
    diff: 'medium',
    mp: true,
    beginner: true,
    gem: true,
    featured: false,
    trending: false,
    year: 2020,
    universeId: 5399537401,
    placeId: 5399537401,
    modes: ['Classic', 'Chaos', 'Competitive'],
  },
  {
    id: 'survive-the-killer',
    title: 'Survive the Killer',
    creator: 'Slyce Entertainment',
    genre: 'social',
    emoji: '🔪',
    desc: 'Asymmetric horror — survivors must escape while one player hunts as a powerful killer. Tense, replayable, brilliantly designed.',
    fullDesc: 'Survive the Killer pits survivors against a single powerful killer in a Dead by Daylight-inspired format. Survivors repair generators, find escape routes, and avoid detection. The killer stalks with unique abilities. The map variety, killer roster, and cat-and-mouse tension make this endlessly replayable.',
    tags: ['Asymmetric', 'Horror', 'Escape', 'DBD-Style', 'Ranked'],
    rating: 88,
    players: 18000,
    playersLabel: '~18K active',
    badge: null,
    diff: 'medium',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2020,
    universeId: 4668711091,
    placeId: 4668711091,
    modes: ['Classic', 'Ranked', 'Custom'],
  },
  {
    id: 'super-bomb-survival',
    title: 'Super Bomb Survival',
    creator: 'polyhex',
    genre: 'social',
    emoji: '💣',
    desc: 'Dodge a barrage of bombs while earning coins and equipping abilities. Classic Roblox chaos done perfectly.',
    fullDesc: 'Super Bomb Survival is pure, joyful chaos. Bombs rain from the sky — dodge them, spend coins on abilities, and outlast other players. The ability system adds variety and the arenas keep things fresh. One of the most reliably fun social games when you want something light and immediately entertaining.',
    tags: ['Chaos', 'Dodge', 'Abilities', 'Classic', 'Party'],
    rating: 85,
    players: 9000,
    playersLabel: '~9K active',
    badge: 'classic',
    badgeText: '🏛 Classic',
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2015,
    universeId: 504116128,
    placeId: 504116128,
    modes: ['Classic', 'Infection'],
  },
  {
    id: 'color-block',
    title: 'Color Block',
    creator: 'ColorBlock Dev',
    genre: 'social',
    emoji: '🟥',
    desc: 'Musical Chairs meets mass-multiplayer — claim colored tiles before round end. 100+ players, infinite chaos.',
    fullDesc: 'Color Block puts hundreds of players on a platform full of colored tiles. When the round ends, players scramble to claim a tile — those without one fall. The pacing is frenetic, the variety of layouts keeps rounds fresh, and the massive multiplayer scale creates hilarious moments. Perfect for groups.',
    tags: ['Party', 'Musical Chairs', 'Massive Multiplayer', 'Quick Rounds'],
    rating: 86,
    players: 80000,
    playersLabel: '~80K active',
    badge: 'new',
    badgeText: '🆕 Trending',
    diff: 'easy',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: true,
    year: 2024,
    universeId: null,
    placeId: null,
    modes: ['Classic', 'Blitz'],
  },

  /* ── PLATFORMER ADDITIONS ───────────────────── */
  {
    id: 'parkour-tag',
    title: 'Parkour Tag',
    creator: 'OmgitsJonas',
    genre: 'platformer',
    emoji: '🏃',
    desc: 'Free-running tag meets obstacle course — chase or flee across dynamic parkour maps. Pure movement skill.',
    fullDesc: 'Parkour Tag divides players into chasers and runners, then lets them loose in elaborate parkour environments. The movement system is smooth and expressive, walls can be run along, rails can be grinded, and the maps reward creativity in traversal. A unique, skill-based hidden gem.',
    tags: ['Parkour', 'Chase', 'Tag', 'Movement', 'Skill'],
    rating: 86,
    players: 8000,
    playersLabel: '~8K active',
    badge: 'hidden-gem',
    badgeText: '💎 Hidden Gem',
    diff: 'medium',
    mp: true,
    beginner: false,
    gem: true,
    featured: false,
    trending: false,
    year: 2023,
    universeId: null,
    placeId: null,
    modes: ['Classic Tag', 'Team Chase'],
  },

  /* ── STRATEGY ADDITIONS ─────────────────────── */
  {
    id: 'bee-swarm-simulator',
    title: 'Bee Swarm Simulator',
    creator: 'Onett',
    genre: 'strategy',
    emoji: '🐝',
    desc: 'Grow your beehive, collect pollen, craft items, and battle bugs. A progression game with genuine depth and a generous developer.',
    fullDesc: 'Bee Swarm Simulator has more depth than it appears. Managing your hive type, bee stats, pollen collection routes, and item crafting creates genuine optimization. Boss events, seasonal updates, and collectible egg hunts keep long-term players engaged. The developer Onett is known for being community-first with no pay-to-win.',
    tags: ['Bees', 'Progression', 'Crafting', 'Collection', 'Casual'],
    rating: 85,
    players: 30000,
    playersLabel: '~30K active',
    badge: null,
    diff: 'easy',
    mp: false,
    beginner: true,
    gem: false,
    featured: false,
    trending: false,
    year: 2018,
    universeId: 1537690962,
    placeId: 1537690962,
    modes: ['Solo', 'Multiplayer Hive'],
  },

  /* ── SPORTS ADDITIONS ───────────────────────── */
  {
    id: 'blade-ball',
    title: 'Blade Ball',
    creator: 'Wiggity',
    genre: 'sports',
    emoji: '⚡',
    desc: 'Deflect an electrified ball toward opponents using timing and abilities. Incredibly viral, deeply skill-based.',
    fullDesc: 'Blade Ball took Roblox by storm with its simple but deep premise: deflect an electrified ball to eliminate opponents using perfectly timed blocks. Each player has unique abilities that can turn the tide. The escalating ball speed and shrinking arena create intense last-player-standing moments. Rounds are short, satisfying, and highly replayable.',
    tags: ['Deflection', 'Timing', 'Abilities', 'Battle Royale', 'Fast Paced'],
    rating: 90,
    players: 65000,
    playersLabel: '~65K active',
    badge: 'new',
    badgeText: '🆕 Trending',
    diff: 'medium',
    mp: true,
    beginner: true,
    gem: false,
    featured: false,
    trending: true,
    year: 2023,
    universeId: 6351012579,
    placeId: 6351012579,
    modes: ['Classic', 'Ranked', 'Private'],
  },
];

/* ── Genre color map ── */
RP.GENRE_COLORS = {
  fps:       'linear-gradient(135deg, #0d1a12 0%, #091018 100%)',
  adventure: 'linear-gradient(135deg, #0d1020 0%, #1a0d20 100%)',
  roleplay:  'linear-gradient(135deg, #0a1a1a 0%, #0a0a1a 100%)',
  horror:    'linear-gradient(135deg, #1a0808 0%, #0a0a12 100%)',
  tycoon:    'linear-gradient(135deg, #1a1508 0%, #081a08 100%)',
  platformer:'linear-gradient(135deg, #1a0808 0%, #1a1508 100%)',
  social:    'linear-gradient(135deg, #080820 0%, #200820 100%)',
  strategy:  'linear-gradient(135deg, #08100a 0%, #0a0a1a 100%)',
  racing:    'linear-gradient(135deg, #1a1008 0%, #0a0808 100%)',
  sports:    'linear-gradient(135deg, #081a08 0%, #081010 100%)',
  building:  'linear-gradient(135deg, #10081a 0%, #0a1010 100%)',
};

/* ── Tips data ── */
RP.TIPS = [
  { icon: '🛡️', title: 'Stay Safe Online', body: 'Never share your Roblox password or personal info in game chat. Enable two-factor authentication on your account. Report anyone asking for account info immediately.' },
  { icon: '💰', title: 'Smart Robux Spending', body: 'Only buy Robux from the official Roblox website. Free Robux generators are always scams. Prioritize cosmetics over gameplay advantages when spending.' },
  { icon: '🎯', title: 'Getting Better at FPS', body: 'Lower your sensitivity, practice in aim trainers, learn map callouts, and focus on positioning before obsessing over raw aim. Consistency beats speed.' },
  { icon: '👥', title: 'Using Private Servers', body: 'Many games offer free or cheap private servers. Great for learning mechanics without pressure, practicing with friends, or exploring without chaos.' },
  { icon: '⚙️', title: 'Performance Settings', body: 'Lower graphics quality in competitive games for better frame rates. The Roblox settings menu lets you adjust this mid-game without restarting.' },
  { icon: '📱', title: 'Mobile vs PC Differences', body: 'FPS and platformers are significantly harder on mobile. Horror and roleplay games work great on phone. Check mobile controls before jumping into a new game.' },
  { icon: '🔍', title: 'Finding Actually Good Games', body: 'Use the Sort by Rating filter instead of Popular. Popular shows trending (often brainrot); Rating shows what players actually enjoy over time.' },
  { icon: '🗺️', title: 'Every Game Has a Wiki', body: 'Stuck in Deepwoken or Doors? Almost every major Roblox game has a community wiki with guides, entity info, and progression maps. Use them freely.' },
];

/* ── Criteria data ── */
RP.CRITERIA = [
  { icon: '🧠', title: 'Skill Required', desc: 'The game rewards practice and improvement — not just the amount of time you\'ve spent.' },
  { icon: '🎮', title: 'Real Objectives', desc: 'Something meaningful to accomplish beyond clicking repeatedly or waiting for timers.' },
  { icon: '⚖️', title: 'Fair Progression', desc: 'Progress is earned through gameplay — not purchases or grinding mechanics designed to frustrate.' },
  { icon: '🔄', title: 'Replayability', desc: 'Each session feels different and interesting, not a copy-paste of the last one.' },
  { icon: '👥', title: 'Community Depth', desc: 'There are things to discuss, create, or compete in beyond the basic game loop.' },
  { icon: '🏗️', title: 'Quality Build', desc: 'The maps, mechanics, and UI show genuine effort from the developers — not asset-flips.' },
];

/* ── Avoid data ── */
RP.AVOID = [
  { icon: '🤖', title: 'Auto-clicker Simulators', desc: 'Tap, collect, upgrade — zero engagement. Designed to waste your time through manufactured dopamine loops.' },
  { icon: '💸', title: 'Pay-to-Win Games', desc: 'Robux purchases that give unfair competitive advantages, making skill irrelevant.' },
  { icon: '🎰', title: 'Gambling Mechanics', desc: 'Egg hatching and case openings with artificially low odds designed to frustrate and extract money.' },
  { icon: '🔁', title: 'Copy-Paste Obbies', desc: 'Identical obstacle courses with nothing unique to offer — thousands of them exist.' },
  { icon: '🐾', title: 'Pure Pet Collectors', desc: 'Collecting pets with no actual gameplay underneath — just inventory management and probability manipulation.' },
  { icon: '📈', title: 'Incremental-Only Games', desc: 'Number goes up — that\'s the entire game. No skill, no story, no substance, no reason to play.' },
];
